# Funding options for InstaToWhatsapp

# Add your GitHub Sponsors account here when ready
# github: [yourusername]

# Or link to external platforms
# ko_fi: yourusername
# patreon: yourusername

# Custom links
custom:
  - "❤️ This is an open-source learning project"
  - "⭐ Star the repo if you find it useful"
  - "🤝 Contributions are welcome!"
